### PR TITLE
Fix load fallback locale when lazy-load and invalid route on update

### PR DESCRIPTION
**Pull request by orblazer**
Hello,
I have merge my 2 PR #260 and #261.

This is fix load fallback locale when lazy-load, before this PR when using local fallback in lazy-load it had no effect, the language was not loading.
This is fix invalid route when update nuxt.config.

This is fix issues #34 and #259.

Thanks.

### CODE REVIEW

**Comment by paulgv** [comment]
I'd need more eyes on this one.
According to [this comment](https://github.com/nuxt-community/nuxt-i18n/issues/259#issuecomment-477045528), this change might actually break the `prefix_except_default` strategy.
It would be best to fix one problem per PR. Also, you've made some formatting changes which makes the PR even harder to review because it makes the relevant changes less visible, I'd recommend you do this kind of changes in a different PR next time.

Thanks for working on this @orblazer !

**Comment by orblazer** [comment]
@rchl you can puck it up because i am currently on project without nuxt and i don't have time before 2 months

**Comment by rchl** [comment]
@orblazer @paulgv created #291 with this fix extracted

**Comment by paulgv** [comment]
Closing in favor of #291

**Pull request closed without merging**
