### PR TITLE
Reworked the browser detection

### PR DESCRIPTION
**Pull request by Magnum5234**
Reworked the browser detection, so that the cookie stores the language. This cookie value is now the preferred value when selecting the browsers locale.
Added the option to redirect every time the user visits the app
Added the options for a fallback locale if no language configured matches the browsers locale
Fixed a bug which lead to redirect loops when redirecting without a cookie

There is currently the issue of how to allow for language switches by the users choice. Accidentally this works when switching language via switchLocalePath because the redirect is not applied (as it is the same). If you have an idea how to "know" in the middleware that the user changed the language explicitly, please let me know (or if you have any other solutions).

Unfortunately I was not able to run the tests locally.

This Pull-Request should (at least partially) cover #114 #106 #86

### CODE REVIEW

**Comment by manniL** [comment]
@Magnum5234 Does that PR introduce any breaking changes?

**Comment by Magnum5234** [comment]
It should work the same as before if you don't use the new configuration values.

**Comment by manniL** [comment]
@Magnum5234 Many thanks for your contribution! 🙏

**Comment by Magnum5234** [comment]
Your are welcome.
If you have an idea about to tackle the language switch issue I would try to fix that, too :)

**Comment by manniL** [comment]
@Magnum5234 Could you provide more details regarding the problem?

**Comment by Magnum5234** [comment]
> There is currently the issue of how to allow for language switches by the users choice. Accidentally this works when switching language via switchLocalePath because the redirect is not applied (as it is the same). If you have an idea how to "know" in the middleware that the user changed the language explicitly, please let me know (or if you have any other solutions).

This is what I wrote initially. 

If you set ```alwaysRedirect``` to _true_ every time the middleware is executed the language will be confirmed that it is up to date with whats stored in the cookie - otherwise redirect. Meaning that the user cannot change the language changing the url. 
If the user triggers the language switch via ```switchLocalePath``` nuxt link the middleware is called with the route still having the old language and the updated locale object. This does trigger the redirect but since the route is not updated yet it does not do anything and in the end it seems to work out. At least that is my understanding. (writing from memory)
There are two ways how to handle the problem
1) ```switchLocalePath``` should also change the cookie - How do you get the context like spa in there?
2) in the middleware check if it's a user triggered language switch and don't try to redirect - how would you do this?

Hope this clarifies things :)

**Comment by manniL** [comment]
That clarifies a lot :relaxed: 

1. The function already accesses the ctx (https://github.com/nuxt-community/nuxt-i18n/blob/513cbf92f9aca614b62c37a96c7476941d0ccf4d/src/plugins/routing.js#L54) once :relaxed: 

2. Probably through the Vuex store. Setting a flag or something there when the language is switched and let the middleware work and unset the flag again

**Comment by Aperrix** [comment]
Hi @Magnum5234 and @manniL, thank you for taking your time to make sure everything works properly !

Being webdesigner i do not quite have the necessary skill to propose a bugfix myself but i take this opportunity to try to improve myself because I need it to work properly as soon as possible to push a new release in production 😓

I hope you find a solution before me because I may take a long time to get there by myself 😄 
so .. thanks again 😃

Love you

**Comment by manniL** [comment]
@Magnum5234 First one sounds suitable, yup!

**Comment by Magnum5234** [comment]
The mentioned redirect bug does not exist, here's why:

Upon clicking on the nuxt-link the middleware is called

The current locale is still the same as before, so is the browser detection value (usually the stored cookie). The route locale on the other hand has the new language.
The alwayRedirect will therefore not trigger because current locale and the browser detection value are still the same
If those are the same and the route locale is set, the locale will be switched to the route locale - and changing the cookie value

examples:

```
GET http://sandbox:3000/
locale: de routeLocale: de cookieValue: de
cookieValue === locale de === de
-> switchLocale(routeLocale) (no change as locale is the same as routeLocale)
```
```
GET http://sandbox:3000/en
locale: en routeLocale: en cookieValue: de
cookieValue !== locale de !== en
-> switchLocale(cookieValue) + redirect

(2nd middleware call)
locale: de routeLocale: de cookieValue: de
cookieValue === locale de === de
-> switchLocale(routeLocale) (no change as locale is the same as routeLocale)
```
```
GET http://sandbox:3000/
(see above)

(switchLocale to en)
locale: de routeLocale: en cookieValue: de
cookieValue === locale de === de
-> switchLocale(routeLocale)
```
```
GET http://sandbox:3000/
(see above)

(switchLocale to /en/secondPage)
locale: de routeLocale: en cookieValue: de
cookieValue === locale de === de
-> switchLocale(routeLocale)
```

(Thanks @manniL for helping me find this not issue)

In the meantime I found some bogus lines (will make a pull request for it tomorrow)

https://github.com/nuxt-community/nuxt-i18n/blob/master/src/templates/middleware.js#L138
(copy paste error, should be `routeLocale ? routeLocale : locale`)

https://github.com/nuxt-community/nuxt-i18n/blob/master/src/templates/middleware.js#L119
(this setCookie is not necessary at it will be set in switchLocale which will be called every time the locale changes)

**Comment by Magnum5234** [comment]
The mentioned redirect bug does not exist, here's why:

Upon clicking on the nuxt-link the middleware is called

The current locale is still the same as before, so is the browser detection value (usually the stored cookie). The route locale on the other hand has the new language.
The alwayRedirect will therefore not trigger because current locale and the browser detection value are still the same
If those are the same and the route locale is set, the locale will be switched to the route locale - and changing the cookie value

examples:

```
GET http://sandbox:3000/
locale: de routeLocale: de cookieValue: de
cookieValue === locale de === de
-> switchLocale(routeLocale) (no change as locale is the same as routeLocale)
```
```
GET http://sandbox:3000/en
locale: en routeLocale: en cookieValue: de
cookieValue !== locale de !== en
-> switchLocale(cookieValue) + redirect

(2nd middleware call)
locale: de routeLocale: de cookieValue: de
cookieValue === locale de === de
-> switchLocale(routeLocale) (no change as locale is the same as routeLocale)
```
```
GET http://sandbox:3000/
(see above)

(switchLocale to en)
locale: de routeLocale: en cookieValue: de
cookieValue === locale de === de
-> switchLocale(routeLocale)
```
```
GET http://sandbox:3000/
(see above)

(switchLocale to /en/secondPage)
locale: de routeLocale: en cookieValue: de
cookieValue === locale de === de
-> switchLocale(routeLocale)
```

(Thanks @manniL for helping me find this not issue)

In the meantime I found some bogus lines (will make a pull request for it tomorrow)

https://github.com/nuxt-community/nuxt-i18n/blob/master/src/templates/middleware.js#L138
(copy paste error, should be `routeLocale ? routeLocale : locale`)

https://github.com/nuxt-community/nuxt-i18n/blob/master/src/templates/middleware.js#L119
(this setCookie is not necessary at it will be set in switchLocale which will be called every time the locale changes)

**Comment by HapLifeMan** [comment]
Hi @Magnum5234, I though your PR fixed this issue because it's a big part of the problem I have, but that's not the case, do you know what happened? https://github.com/nuxt-community/nuxt-i18n/issues/166

**Comment by manniL** [comment]
@HapLifeMan Be aware that this PR is not included it any release yet

**Comment by HapLifeMan** [comment]
@manniL Yes I used the commit reference 😊

**Comment by BroTrue** [comment]
@manniL is this PR on release ? Because I still go same issue.  **"nuxt-i18n": "5.8.0",**

My `nuxt.config.js`
```
...
  modules: [

    ['nuxt-i18n', {
      locales: [
          { code: 'ru', iso: 'ru-RU'},
        { code: 'en', iso: 'en-US' },
        { code: 'ua', iso: 'ua-UA' }
        ],
      defaultLocale: 'ru',
      detectBrowserLanguage: {
        useCookie: true,
        cookieKey: 'i18n_redirected',
      alwaysRedirect: true
      },
      vueI18n: {
        fallbackLocale: 'ru',
        messages: {
          'ru': require('./locales/ru.json'),
          'en': require('./locales/en.json'),
          'ua': require('./locales/ua.json')
        }
      },
    }],
...
```

**Comment by manniL** [comment]
@BroTrue should be, yup. 
image

**Comment by BroTrue** [comment]
Maybe @Magnum5234 can help me with my problem ? Also i noticed that `switchLocalePath()` is changing local at Vuex, but NOT changing cookies value.

**Comment by Magnum5234** [comment]
@BroTrue Do you mean the same issue as @HapLifeMan is having? I will have a look at this.

@HapLifeMan Sorry I did not see the post in December, missed the email somehow. I will have a look at this asap.

**Comment by manniL** [comment]
Better talk about that in a new issue guys

**Comment by BroTrue** [comment]
Ok, I will create it soon.

**Pull request merged**
