### PR TITLE
feat(loadLanguageAsync): Support promises return in lang files

### PR DESCRIPTION
**Pull request by ezypeeze**
Based on this feature request that I opened myself: 
https://github.com/nuxt-community/nuxt-i18n/issues/60

### CODE REVIEW

**Comment by paulgv** [comment]
Nice! thanks @ezypeeze !

**Comment by liuhuanhui** [comment]
Hello, you can provide an example

**Comment by git-antonyuk** [comment]
**Hi all! First of all, thank you for all your hard work!**

In example above we fetching all data of one language for all app, but, if we have a lot of data? 
Is there any proper way to load data, lets say some local GlobalData (Header and Footer) and data of only one page (local) wich is loading? Or maybe, better solution is to use middleware and mutations build in nuxt-i18n config (I18N_SET_MESSAGES).   

In my new project, I geting data from firebase and it works great, but project is growing and I looking for better solution for fetching data, so to say, by small piece. Code example:

```javascript 
import axios from 'axios';
import Vue from 'vue';

Vue.use(axios);

export default () => {
  return axios.get('https://bla-bla-bla.firebaseio.com/en.json')
  .then(function (response) {
    return response.data;
  })
  .catch(function (error) {
    error;
  });
}
```

**Comment by desislavsd** [comment]
Hey, is there a way to provide a single function to nuxt-i18n that accepts `lang` parameter and avoid creating all the lang files?

**Pull request merged**
