### PR TITLE
Bump js-cookie version to 2.2.1

### PR DESCRIPTION
**Pull request by fians**
I hope this doesn't break anything.

### CODE REVIEW

**Comment by fians** [comment]
Oops..

**Comment by fians** [comment]
Weird, in circleci test-e2e-ssr failed, but in my machine is working fine. Here is the output.

```
$ jest test/module.test
 PASS  test/module.test.js (92.716s)
  basic
    √ sets SEO metadata properly (119ms)
    √ / contains EN text, link to /fr/ & link /about-us (23ms)
    √ /fr contains FR text, link to / & link to /fr/a-propos (15ms)
    √ /about-us contains EN text, link to /fr/a-propos & link / (16ms)
    √ /fr/a-propos contains FR text, link to /about-us & link to /fr/ (17ms)
    √ /fr/notlocalized contains FR text (12ms)
    √ /notlocalized & /fr/fr/notlocalized return 404 (12ms)
    √ route specifies options with non-supported locale (15ms)
    √ navigates to child route with nameless parent and checks path to other locale (70ms)
    √ navigates to dynamic child route and checks path to other locale (66ms)
    √ /dynamicNested/1/2/3 contains link to /fr/imbrication-dynamique/1/2/3 (25ms)
    √ /fr/imbrication-dynamique/1/2/3 contains link to /dynamicNested/1/2/3 (16ms)
    √ localePath returns correct path (55ms)
    √ switchLocalePath returns correct path (53ms)
    √ getRouteBaseName returns correct name (58ms)
    √ localePath, switchLocalePath, getRouteBaseName works from a middleware (11ms)
    √ redirects to existing route (56ms)
    √ fallbacks to default locale with invalid locale cookie (13ms)
    √ registers message using vueI18nLoader (12ms)
    posts
      √ /posts contains EN text, link to /fr/articles/ & link to /posts/my-post (22ms)
      √ /posts/my-post contains EN text, link to /fr/articles/mon-article & link to /posts/ (13ms)
      √ /fr/articles contains FR text, link to /posts/ & link to /fr/articles/mon-article (14ms)
      √ /fr/articles/mon-article contains FR text, link to /posts/my-post & link to /fr/articles/ (17ms)
    store
      √ injects $i18n in store (187ms)
      √ syncs i18n locale and messages (75ms)
  lazy loading
    √ shows fallback string (37ms)
  with empty configuration
    √ does not remove all routes (90ms)
  prefix_and_default strategy
    √ default locale routes / and /en exist (39ms)
    √ non-default locale route /fr exists (8ms)
    √ canonical SEO link is added to prefixed default locale (16ms)
    √ canonical SEO link is not added to non-prefixed default locale (14ms)
  no_prefix strategy
    √ sets SEO metadata properly (56ms)
    √ / contains EN text & link /about (20ms)
    √ /about contains EN text & link / (14ms)
    √ /fr/ returns 404 (6ms)
    √ localePath returns correct path (96ms)
    √ localePath with non-current locale triggers warning (57ms)
    √ fallbacks to default locale with invalid locale cookie (11ms)
  no_prefix strategy + differentDomains
    √ triggers warning (5625ms)
  invalid strategy
    √ triggers error on building (8381ms)
  dynamic route
    √ can access catch-all route for every locale (114ms)
  hash mode
    √ localePath returns correct path (without hash) (168ms)
  with router base
    √ localePath returns correct path (132ms)
  differentDomains enabled
    √ matches domain's locale (en) (43ms)
    √ matches domain's locale (fr) (13ms)
  parsePages disabled
    √ navigates to route with paths defined in pages option (93ms)
    √ navigates to route with paths disabled in pages option (16ms)

----------------|----------|----------|----------|----------|-------------------|
File            |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------------|----------|----------|----------|----------|-------------------|
All files       |    99.22 |    92.77 |      100 |    99.17 |                   |
 src            |      100 |    83.33 |      100 |      100 |                   |
  index.js      |      100 |    83.33 |      100 |      100 |     32,58,109,118 |
 src/helpers    |    98.81 |    96.61 |      100 |    98.72 |                   |
  components.js |       95 |      100 |      100 |       95 |                46 |
  routes.js     |      100 |    96.08 |      100 |      100 |             20,80 |
----------------|----------|----------|----------|----------|-------------------|
Test Suites: 1 passed, 1 total
Tests:       47 passed, 47 total
Snapshots:   0 total
Time:        93.093s
Ran all test suites matching /test\\module.test/i.
Done in 94.42s.
```

However, i got failure test when running `browser.test.js`. Here is the output.

```
$ jest test/browser.test
  console.info node_modules/tib/lib/tib-browser.js:201
    tib: Static server started on http://localhost:54551

 FAIL  test/browser.test.js (31.548s)
  puppeteer/core
    × navigate with SPA (2502ms)
    × APIs in app context work after SPA navigation (167ms)
  puppeteer/core (generate)
    × navigate to non-default locale (522ms)
  puppeteer/core (SPA with router in hash mode)
    √ navigates directly to page with trailing slash (521ms)
    √ navigates directly to page with query (173ms)

  ● puppeteer/core › navigate with SPA

    Evaluation failed: TypeError: Cannot read property 'then' of undefined

      at eval (eval at <anonymous> (:2:17), <anonymous>:1:39)
      at __puppeteer_evaluation_script__:2:60
      at ExecutionContext._evaluateInternal (node_modules/puppeteer-core/lib/ExecutionContext.js:122:13)
        -- ASYNC --
      at ExecutionContext.<anonymous> (node_modules/puppeteer-core/lib/helper.js:111:15)
      at DOMWorld.evaluate (node_modules/puppeteer-core/lib/DOMWorld.js:112:20)
        -- ASYNC --
      at Frame.<anonymous> (node_modules/puppeteer-core/lib/helper.js:111:15)
      at Page.evaluate (node_modules/puppeteer-core/lib/Page.js:863:43)
      at Page.<anonymous> (node_modules/puppeteer-core/lib/helper.js:112:23)
      at Proxy.runScript (node_modules/tib/lib/tib-core.js:49:22)
      at Proxy.runAsyncScript (node_modules/tib/lib/tib-webpage.js:86:17)
      at Proxy.navigate (test/browser.test.js:13:16)
      at Object.test (test/browser.test.js:52:16)

  ● puppeteer/core › APIs in app context work after SPA navigation

    Evaluation failed: TypeError: Cannot read property 'then' of undefined

      at eval (eval at <anonymous> (:2:17), <anonymous>:1:39)
      at __puppeteer_evaluation_script__:2:60
      at ExecutionContext._evaluateInternal (node_modules/puppeteer-core/lib/ExecutionContext.js:122:13)
        -- ASYNC --
      at ExecutionContext.<anonymous> (node_modules/puppeteer-core/lib/helper.js:111:15)
      at DOMWorld.evaluate (node_modules/puppeteer-core/lib/DOMWorld.js:112:20)
        -- ASYNC --
      at Frame.<anonymous> (node_modules/puppeteer-core/lib/helper.js:111:15)
      at Page.evaluate (node_modules/puppeteer-core/lib/Page.js:863:43)
      at Page.<anonymous> (node_modules/puppeteer-core/lib/helper.js:112:23)
      at Proxy.runScript (node_modules/tib/lib/tib-core.js:49:22)
      at Proxy.runAsyncScript (node_modules/tib/lib/tib-webpage.js:86:17)
      at Proxy.navigate (test/browser.test.js:13:16)
      at Object.test (test/browser.test.js:64:16)

  ● puppeteer/core (generate) › navigate to non-default locale

    Evaluation failed: TypeError: Cannot read property 'then' of undefined

      at eval (eval at <anonymous> (:2:17), <anonymous>:1:39)
      at __puppeteer_evaluation_script__:2:60
      at ExecutionContext._evaluateInternal (node_modules/puppeteer-core/lib/ExecutionContext.js:122:13)
        -- ASYNC --
      at ExecutionContext.<anonymous> (node_modules/puppeteer-core/lib/helper.js:111:15)
      at DOMWorld.evaluate (node_modules/puppeteer-core/lib/DOMWorld.js:112:20)
        -- ASYNC --
      at Frame.<anonymous> (node_modules/puppeteer-core/lib/helper.js:111:15)
      at Page.evaluate (node_modules/puppeteer-core/lib/Page.js:863:43)
      at Page.<anonymous> (node_modules/puppeteer-core/lib/helper.js:112:23)
      at Proxy.runScript (node_modules/tib/lib/tib-core.js:49:22)
      at Proxy.runAsyncScript (node_modules/tib/lib/tib-webpage.js:86:17)
      at Proxy.navigate (test/browser.test.js:13:16)
      at Object.test (test/browser.test.js:111:16)

----------------|----------|----------|----------|----------|-------------------|
File            |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------------|----------|----------|----------|----------|-------------------|
All files       |    85.94 |    66.27 |      100 |    85.12 |                   |
 src            |    90.91 |    54.17 |      100 |     90.7 |                   |
  index.js      |    90.91 |    54.17 |      100 |     90.7 |       39,40,76,78 |
 src/helpers    |    83.33 |    71.19 |      100 |    82.05 |                   |
  components.js |       95 |      100 |      100 |       95 |                46 |
  routes.js     |    79.69 |    66.67 |      100 |    77.59 |... 99,103,104,105 |
----------------|----------|----------|----------|----------|-------------------|
Test Suites: 1 failed, 1 total
Tests:       3 failed, 2 passed, 5 total
Snapshots:   0 total
Time:        31.875s
Ran all test suites matching /test\\browser.test/i.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! Test failed.  See above for more details.
```

**Comment by fians** [comment]
I've updated yarn.lock and test running fine on my machine, and now I have no idea why the test is failed on circle ci.

**Comment by rchl** [comment]
No need to create separate PR for this. This is just a minor dependency update and is normally handled by automatic lock file maintenance PRs that happen every Friday (I can also retry the one that is currently open).

**Comment by rchl** [comment]
No, sorry, that's not entirely true. `renovate` only handles devDependencies.
For `js-cookie`, since the version is specified as a range (`^2.2.0`), it doesn't prevent anyone from using the latest version of that dependency. Is it really necessary to manually change it to require at least `2.2.1`?

**Comment by rchl** [comment]
Although I see the point that explicitly upping it will force people to use the latest version which might be worth it if there is a security fix there.

**Comment by rchl** [comment]
BTW. There might be some issues with circleci. Will try to find out what's happening there.

**Comment by fians** [comment]
@rchl Thanks for the response. This PR is not required though, I just think it would be nice if the library has the latest version of its dependencies. Feel free to close the PR, if you think it is not the important things that need to be working on right now. 👍

**Comment by rchl** [comment]
That's OK, I'll merge it since it seems to include security-related fix. Just fixing the testing issue first. Thanks. :)

**Comment by rchl** [comment]
Can you rebase your change on master? It should pass testing next time.

**Comment by fians** [comment]
@rchl Now everything works fine. 👍

**Comment by rchl** [comment]
Thanks!

**Pull request merged**
