### PR TITLE
Fix #173

### LINKED ISSUE #173: Cannot set property 'locale' of undefined
### Version

[v5.3.0](https://github.com/nuxt-i18n/releases/tag/v5.3.0)

### Reproduction link

- demo: [https://willin.guru](https://willin.guru)
- source: https://github.com/willin/willin.github.io

### Steps to reproduce

when development mode it's ok, but when built and deployed it shown error.

### What is expected ?

works properly

### What is actually happening?

```
c6b25ed7d1e571a9b85f.js:1 [nuxt] Error while initializing app TypeError: Cannot set property 'locale' of undefined
    at f.<anonymous> (c6b25ed7d1e571a9b85f.js:1)
    at 33b42310abd05a803713.js:2
    at 33b42310abd05a803713.js:2
    at Array.forEach (<anonymous>)
    at 33b42310abd05a803713.js:2
    at f._withCommit (33b42310abd05a803713.js:2)
    at f.commit (33b42310abd05a803713.js:2)
    at f.commit (33b42310abd05a803713.js:2)
    at o.commit (33b42310abd05a803713.js:2)
    at f.setLocale (c6b25ed7d1e571a9b85f.js:1)
```

source code: https://github.com/nuxt-community/nuxt-i18n/blob/master/src/plugins/main.js#L41

wx20181230-005037 2x

state got `undefined`

### Additional comments?

Config:

```js
  modules: [
    ['nuxt-i18n', {
      locales: [
        { name: '简体中文', code: 'zh', iso: 'zh-CN', file: 'zh.js' },
        { name: 'English', code: 'en', iso: 'en-US', file: 'en.js' }
      ],
      lazy: true,
      langDir: 'locales/',
      strategy: 'prefix',
      defaultLocale: 'zh',
      detectBrowserLanguage: {
        useCookie: true,
        cookieKey: 'i18n_redirected'
      },
      rootRedirect: 'en',
      vueI18n: {
        fallbackLocale: 'en'
      }
    }]
  ],
```

deployed files: https://dev.tencent.com/u/willin/p/willin.wang/git/tree/master

- ROOT
 - 404.html
 - zh/ folder
 - en/ folder 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c183">#c183</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by priezz**

### CODE REVIEW

**Comment by michaelize** [comment]
https://github.com/nuxt-community/nuxt-i18n/pull/163 seems related

**Comment by priezz** [comment]
@michaelize Probably not, because disabling lazy loadyn does not prevent #173 from appearing.

**Comment by michaelize** [comment]
Thanks for the info. Would like to find out why the state is not defined here. Knowing lazy loading is not the issue helps.

**Comment by michaelize** [comment]
I think I've identified the root cause, and pushed a fix here: https://github.com/nuxt-community/nuxt-i18n/pull/178

**Comment by paulgv** [comment]
Hi! Let me know if this can be closed of if should be merged along with #178, thanks!

**Comment by paulgv** [comment]
Closing in favor or https://github.com/nuxt-community/nuxt-i18n/pull/178

**Pull request closed without merging**
