### PR TITLE
Remove forwardedHost parameter

### PR DESCRIPTION
**Pull request by maxm86545**
Remove forwardedHost for simplify. Ignore port when matching locale domain (it's a solution for working SSR: https://github.com/nuxt-community/nuxt-i18n/pull/627#discussion_r391029596).

### CODE REVIEW

**Comment by rchl** [comment]
This change has the potential to break someone's use case so I wonder if it should be a breaking change...

I guess it will only change behavior when someone has `x-forwarded-host` header but didn't want to use it before. But that would likely result in broken functionality with `differentDomains` so I will probably just treat it as a bug fix.

I'm not sure how does it fix your case though. It seems equivalent to the old code when it comes to the server-side.
For client-side there will be a change again, as `location.href.split('/')[2]` returned port (didn't notice that before) while `location.hostname` won't.

So before merging this, I would like to understand your case. Are your public URLs include the port (for example https://foo.com:888 ?). How would this fix help here for `differentDomains` functionality?

**Comment by maxm86545** [comment]
> I guess it will only change behavior when someone has x-forwarded-host header but didn't want to use it before.

Someone doesn't want to use x-forwarded-host header? Does this person exist?

> For client-side there will be a change again, as location.href.split('/')[2] returned port (didn't notice that before) while location.hostname won't.

Yes, `location.href.split('/')[2]` return port on client-side, and `req.headers['x-forwarded-host']` or `req.headers.host` don't return port on server-side. I did the same behavior on client and server.

> So before merging this, I would like to understand your case. Do your public URLs include the port (for example https://foo.com:888 ?). How would this fix help here for differentDomains functionality?

Yes, my public URLs include the port. For example: foo.com:888 - English, fr.foo.com:888 - French, es.foo.com:888 - Spanish.

**Comment by rchl** [comment]
Still, don't understand how this helps. You still won't pass the port when redirecting.

**Comment by maxm86545** [comment]
I specify domains in the nuxt.config.js without ports:

> i18n: {
        locales: [
            {
                name: 'English',
                domain: 'foo.com',
                ...
            },
            {
                name: 'French',
                domain: 'fr.foo.com',
                ...
            },
            {
                name: 'Spanish',
                domain: 'es.foo.com',
                ...
            },
        ],
         ...
}

**Comment by rchl** [comment]
And so nuxt-i18n will redirect without port included and it won't work as far as I can see.

**Comment by maxm86545** [comment]
This solution works for me. For me the port is not important, because it does not change locale. Only different domains change locale.

**Comment by maxm86545** [comment]
> And so nuxt-i18n will redirect without port included and it won't work as far as I can see.

Do you mean switchLocalePath redirect without port?

**Comment by rchl** [comment]
No, i mean different domains functionality that will still not work properly.
Or maybe tell me what was the issue without this fix? Exactly. How did it behave and when

**Comment by maxm86545** [comment]
> Or maybe tell me what was the issue without this fix? Exactly. How did it behave and when

Ок.
My public URLs include the port. For example: foo.com:888 - English, es.foo.com:888 - Spanish.

My nuxt.config.js is:
> i18n: {
        locales: [
            {
                name: 'English',
                code: 'en',
                iso: 'en',
                domain: 'foo.com:888',
            },
            {
                name: 'Spanish',
                code: 'es',
                iso: 'es',
                domain: 'es.foo.com:888',
            },
        ],
        differentDomains: true,
        forwardedHost: true, // I tried using true and false
         ...
}

I use Nginx proxy:
foo.com:888 -> (with headers `Host: foo.com` and  `X-Forwarded-Host: foo.com`) node.js (nuxt) server
es.foo.com:888 ->  (with headers `Host: es.foo.com` and  `X-Forwarded-Host: es.foo.com`) node.js (nuxt) server

I have problems with translation on server-side, SSR is not working. Translation works on client-side.

**Comment by rchl** [comment]
Well, no you are saying something else than before (previously you said you don't have ports in configuration).

But anyways, even with the fix I still don't see how it will work. The `getLocaleDomain` will return null (as `domain` setting and `x-forwarded-host` won't match) and locale won't match the domain.

**Comment by maxm86545** [comment]
With this fix I specify domains in the `nuxt.config.js` without ports. The `getLocaleDomain` return correct locale domain.

**Comment by rchl** [comment]
This change changes nothing for that case, as far as I can see. At least for the server-side requests.

With this configuration:
```
i18n: {
        locales: [
            {
                name: 'English',
                code: 'en',
                iso: 'en',
                domain: 'foo.com:888'
            },
            {
                name: 'Spanish',
                code: 'es',
                iso: 'es',
                domain: 'es.foo.com:888'
            },
        ],
        differentDomains: true,
        forwardedHost: true, // I tried using true and false
         ...
}
```
Both before this change and after, the `x-forwarded-host` would not batch `domain` and the locale wouldn't be applied according to domain.

Please, give me full details instead of partial responses. I feel like we are running in circles.

**Comment by rchl** [comment]
And the same if you don't include ports in Nuxt configuration. The behavior should still be the same both before and after this change.

While I don't mind this change (I think it simplifies things), I don't understand how to fixed your issue. I want to understand that as it would be good to also have test for that.

**Comment by maxm86545** [comment]
Your comment: https://github.com/nuxt-community/nuxt-i18n/pull/630#issuecomment-598053277
> location.href.split('/')[2] returned port (didn't notice that before) while location.hostname won't.

https://github.com/nuxt-community/nuxt-i18n/blob/eeb63bb701d1b76804790e87ef8cabe9149fdb9a/src/templates/utils.js#L157
On client-side the `nuxtI18n.forwardedHost ? getForwarded(req) : getHostname(req)` return host with port, and on server-side return host without port. `const hostname` on client-side not equals on server-side. This creates a problem with SSR. My fix solves this problem. And I find the forwardedHost parameter redundant, so I suggest removing it.

**Comment by rchl** [comment]
OK.
I would think that creates problem on the client (SPA) and not server (SSR) but OK, at least I understand your problem now.

**Comment by maxm86545** [comment]
Additionally, maybe we can add the key `port` for locales? For example:

```
locales: [
     {
          name: 'English',
          code: 'en',
          iso: 'en',
          domain: 'foo.com',
          port: 888
    },
    {
          name: 'Spanish',
          code: 'es',
          iso: 'es',
          domain: 'es.foo.com:888',
          port: 888
    },
    ...
]
```

This nee

**Comment by rchl** [comment]
I've also added some tests in 3f4d13577bbca02e3b8d4bdd156a7854a95c7f0d and added deprecation warning for that setting.

**Comment by jensgeffken** [comment]
Is this warning only temporary ? Till the next iteration ? Because i have this warning in an universal ssr nuxt app since over 2 weeks and i cant figure the instructions given to resolve this. Thanks

**Comment by rchl** [comment]
@jensgeffken Just don't set `forwardedHost` in options passed to the module.

**Comment by jensgeffken** [comment]
> @jensgeffken Just don't set `forwardedHost` in options passed to the module.

you mean in nuxt.config.js ?

I did this ...

['nuxt-i18n', {
      detectBrowserLanguage: {
        useCookie: true,
        cookieKey: 'language_redirect',
        alwaysRedirect: true,
        fallbackLocale: 'en'
      },
      defaultLocale: 'de',
      strategy: 'prefix_except_default',
      baseUrl: process.env.NODE_ENV === 'development' ? 'http://localhost:8888' : 'https://www.example.com',
      seo: false,
      locales: [
        {
          code: 'en',
          iso: 'en-US',
          file: 'en-US.js',
          name: 'English'
        },
        {
          code: 'de',
          iso: 'de-DE',
          file: 'de-DE.js',
          name: 'Deutsch'
        }
      ],
      lazy: true,
      langDir: 'languages/'
    }]

still the warning ... dang

**Comment by rchl** [comment]
Which warning are you talking about? With that config, you wouldn't get any warning about `forwardedHost`.

**Comment by jensgeffken** [comment]
> Which warning are you talking about? With that config, you wouldn't get any warning about `forwardedHost`.

mmh nope still getting the error in universal ssr app without forwardedHost or forwardedHost set to false in nuxt.config.js

**Comment by rchl** [comment]
Please copy-paste exact erro.

**Comment by jensgeffken** [comment]
> Please copy-paste the exact warning you are getting.

 WARN  [undefined] The forwardedHost option is deprecated. You can safely remove it. See: https://github.com/nuxt-community/nuxt-i18n/pull/630.

My config is like the one i showed, running: nuxt (v2.12.1) universal ssr, in dev mode, when starting the app with npm run dev, i ll get the mentioned warning ...

**Comment by rchl** [comment]
The warning is harmless but I don't see how it would trigger unless you have some weird issues with build files (like module's code partially being new and partially old).

I'd recommend deleting `node_modules`, deleting `.nuxt` build directory and then reinstalling dependencies and starting next again.

If you have an issue with the warning then that might be sign of some deeper issue that could cause other problems so I recommend you try what I wrote above.

**Comment by jensgeffken** [comment]
ok, thanks a lot

**Comment by sowinski** [comment]
Hi guys,

updated nuxt-i18n from version 6.4.1 to 6.11.1 and I am using x-forwarded-host.

Nuxt-i18n is currently not picking up the correct translation. I do not understand what I have to change. Can someone explain it? Or is this somewhere documented?

**Comment by rchl** [comment]
There is no option anymore because `x-forwarded-host` is always taken into consideration now.

If something doesn't work then your best bet is to create an issue and provide more information in it.

**Comment by jensgeffken** [comment]
the message still appears 👎 
` WARN  [undefined] The forwardedHost option is deprecated. You can safely remove it. See: https://github.com/nuxt-community/nuxt-i18n/pull/630.`
guess its one of those things, i will ignore it, everything else works fine

**Comment by rchl** [comment]
@jensgeffken This message triggers when there is a `forwardedHost` key in options. And the module itself doesn't add that key at any place in the code. So it's coming from your project somehow.

You can look at generated file in `.nuxt/nuxt-i18n/options.js` to check what the options you are passing to the module include. If you have `forwardedHost` there then it's coming from somewhere in your project.

**Comment by jensgeffken** [comment]
> @jensgeffken This message triggers when there is a `forwardedHost` key in options. And the module itself doesn't add that key at any place in the code. So it's coming from your project somehow.
> 
> You can look at generated file in `.nuxt/nuxt-i18n/options.js` to check what the options you are passing to the module include. If you have `forwardedHost` there then it's coming from somewhere in your project.

hello @rchl thanks for the reply, i found it in my config and successfully removed it. My mistake thanks again.

**Pull request merged**
